services:
  server:
    restart: always
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    volumes:
      - /usr/src/app
    depends_on:
      - localhost
    networks:
      - express-mongo
    ports:
      - 5000:5000
  localhost:
    restart: always
    image: mongo:4.2.0
    volumes:
      - ./data:/data/db
    networks:
      - express-mongo
    expose:
      - 27017
networks:
  express-mongo: