name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - uses: peaceiris/actions-gh-pages@v3
    
    - name: Install dependencies
      run: npm ci

    - name: Build Docker image
      run: docker buildx build -t jwt .

    - name: Start Docker Compose
      run: docker-compose up -d

    - name: Stop Docker Compose
      run: docker-compose down

    
